// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ElectricityPriceWebApi.Models
{
    public partial class ElectricityPriceContext : DbContext
    {
        public ElectricityPriceContext()
        {
        }

        public ElectricityPriceContext(DbContextOptions<ElectricityPriceContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ElectricityPrice> ElectricityPrices { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ElectricityPrice>(entity =>
            {
                entity.ToTable("ElectricityPrice", "ElectricityPrice");

                entity.Property(e => e.CountryCode)
                    .IsRequired()
                    .HasColumnType("character varying");

                entity.Property(e => e.InEffectFrom).HasColumnType("timestamp without time zone");

                entity.Property(e => e.InEffectTo).HasColumnType("timestamp without time zone");

                entity.Property(e => e.UpdatedAt).HasColumnType("timestamp without time zone");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}